# Generated by Django 5.2.1 on 2025-05-19 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clientefinal_criado_em_clientefinal_usuario_and_more'),
        ('pedidos', '0002_carrinho_atualizado_em_carrinho_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientefinal'),
        ),
    ]
