# Generated by Django 5.2.1 on 2025-05-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clientefinal_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefinal',
            name='email_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
