# Generated by Django 5.2.1 on 2025-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clientefinal_email_confirmado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientefinal',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='clientefinal',
            name='usuario',
        ),
        migrations.AddField(
            model_name='clientefinal',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='clientefinal',
            name='senha',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientefinal',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
